### ISSUE TITLE
command running under --env=prod

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/ecommerce#2]
**Framework Version: 1.0**

1 Ecommerce bundle already updated inside project's apps/uvdesk directory
2 .env update to env= prod
Now, execute command: php bin/console doctrine:migrations:diff

Getting Warning message
![ecomm1](https://user-images.githubusercontent.com/43210406/65493477-88ba8600-ded0-11e9-925c-14c371fd4489.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul  
Make sure your environment is set to **APP_ENV=dev**  in **.env file** while installing this package.
