### ISSUE TITLE
compatibility with composer v2.0

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/ecommerce#4]
composer latest version >  2.0

Getting error when install apps inside **apps/uvdesk/**

run the command
php bin/console uvdesk_extensions:configure-extensions

![Screenshot_219](https://user-images.githubusercontent.com/43210406/104813700-dd55e300-5830-11eb-9127-861cde1b3f42.png)

![Screenshot_218](https://user-images.githubusercontent.com/43210406/104813681-c1524180-5830-11eb-89fb-fb60dcb4fed6.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Now compatible with php 8 as well as with composer 2
